### PR TITLE
Cleanup generated files and add GitHub's default .gitignore for Dart

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jacobaraujo7** [comment]
some files like puubspec.lock is very important.

**Comment by jpnurmi** [comment]
https://dart.dev/guides/libraries/private-files

**Comment by jpnurmi** [comment]
Oh right, and this is an app not a lib. What was I thinking :D

**Comment by jpnurmi** [comment]
Alright, rebased to resolve conflicts with https://github.com/Flutterando/slidy/commit/9bb98198ea53a5e6c75ca8d5c1611faaeb94 (a perfect example of why you don't want to have these generated files in the repo) and updated to keep pubspec.lock intact.

**Comment by jpnurmi** [comment]
Just to elaborate, right now if you have a clean checkout of Slidy, pub run fails for anyone except bwolf on Windows:
```
$ pub run bin/main.dart 
Unable to spawn isolate: bin/main.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/args.dart': No such file or directory
import 'package:args/args.dart';
       ^
bin/main.dart:2:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/run_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/command_base.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/install_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/uninstall_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/update_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/create_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/sub_command/generate_module_sub_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
lib/src/command/sub_command/generate_page_sub_command.dart:1:8: Error: Error when reading '/C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/args-1.5.2/lib/command_runner.dart': No such file or directory
import 'package:args/command_runner.dart';
       ^
```
As soon as you run pub get to fix the problem, you'll get modifications to version controlled files:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .dart_tool/package_config.json
	modified:   .packages

no changes added to commit (use "git add" and/or "git commit -a")
```
The diff looks like:
```diff
$ git diff
diff --git a/.dart_tool/package_config.json b/.dart_tool/package_config.json
index 72c313b..1ce821e 100644
--- a/.dart_tool/package_config.json
+++ b/.dart_tool/package_config.json
@@ -3,343 +3,343 @@
   "packages": [
     {
       "name": "_fe_analyzer_shared",
-      "rootUri": "file:///C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/_fe_analyzer_shared-1.0.1",
+      "rootUri": "file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-1.0.1",
       "packageUri": "lib/",
       "languageVersion": "2.2"
     },
     {
       "name": "analyzer",
-      "rootUri": "file:///C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-0.39.2+1",
+      "rootUri": "file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2+1",
       "packageUri": "lib/",
       "languageVersion": "2.2"
     },
     <...about 7 screens of similar diff left out...>
@@ -350,7 +350,7 @@
       "languageVersion": "2.7"
     }
   ],
-  "generated": "2020-03-25T01:43:32.275180Z",
+  "generated": "2020-05-21T11:43:49.729276Z",
   "generator": "pub",
-  "generatorVersion": "2.8.0-dev.16.0.flutter-ba8baa46b4"
+  "generatorVersion": "2.8.2"
 }
diff --git a/.packages b/.packages
index c8cb0d6..d9e3db9 100755
--- a/.packages
+++ b/.packages
@@ -1,59 +1,59 @@
-# Generated by pub on 2020-03-24 22:43:32.253179.
-_fe_analyzer_shared:file:///C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/_fe_analyzer_shared-1.0.1/lib/
-analyzer:file:///C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-0.39.2+1/lib/
-ansicolor:file:///C:/Users/bwolf/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/ansicolor-1.0.2/lib/
<...1 screen of similar diff left out>
+# Generated by pub on 2020-05-21 13:43:49.711670.
+_fe_analyzer_shared:file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-1.0.1/lib/
+analyzer:file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2+1/lib/
+ansicolor:file:///home/jpnurmi/.pub-cache/hosted/pub.dartlang.org/ansicolor-1.0.2/lib/
<...1 screen of similar diff left out>
```
Check the history of these files and you'll see 3-4 "contributors" to these generated files, with changes playing ping-pong with usernames and timestamps... Do you really want every contributor in their turn to commit their usernames to these files, resulting to extra noise in PRs and Git history?

**Pull request merged**
